### ISSUE TITLE
lanshark.conf file located in the wrong location

### ISSUE THREAD

**Issue by adityathiru** [zense/media_hub#1]
Expected Location : ~/.config/lanshark
Actual Location : ./lanshark/bin/\~\\lanshark
```
 | For linux config file is located in                     |
 | $XDG_CONFIG_HOME/lanshark/config. Which points normally |
 | to ~/.config/lanshark/config                            |
 |                                                         |
 | If you've used the windows installer the config file    |
 | will be located in your home directory and called       |
 | lanshark.conf                                           |
 |                                                         |
 | For the portable windows version the config file        |
 | is located in the conf folder and called lanshark.conf  |
 |                                                         |
 | The config file is pretty self descriptive.             |
 | Just look at the comments (the lines starting           |
 | with a #).                 
```
Look into src/config.py for more info

**Comment by adityathiru** [comment]
Current code works when the lanshark.conf is located at ./lanshark/bin/~\lanshark.
Go through the code, and try changing the location to ~/.config/lanshark.

**Comment by adityathiru** [comment]
Assigned to : @adishegde 
Please update your status here

**Comment by adishegde** [comment]
The problem lies in how the platform is checked for Windows.

The current code is:
```python
if "win" in sys.platform:
```

however, `sys.platform` returns `darwin` for Mac and so the path is incorrectly set.

I have fixed this. Will submit a PR after templates have been issued.

**Comment by adityathiru** [comment]
Cool. Have you modified the code to move the config file to the Expected Location : ~/.config/lanshark ?

**Comment by adishegde** [comment]
Yes.

**Comment by adityathiru** [comment]
Okay. 
Test it from your end and confirm the working of share_path, incoming_path etc. (esp with different versions of osx - atleast the latest one like sierra and high sierra).

**Comment by vik-y** [comment]
@adishegde Waiting for the PR :D
