### ISSUE TITLE
lansharkgui not working on macOS

### ISSUE THREAD

**Issue by adityathiru** [zense/media_hub#3]
- Issue resides in pygtk compatibility.
- Alternate method of installation has to be tested from pygtk website.
- Error log on trying to install pygtk through pip on macOS : 
```
Collecting pygtk
  Using cached pygtk-2.24.0.tar.bz2
    Complete output from command python setup.py egg_info:
    ********************************************************************
    * Building PyGTK using distutils is only supported on windows. *
    * To build PyGTK in a supported way, read the INSTALL file.    *
    ********************************************************************
```
- Look for an alternate method of installation.

**Comment by adityathiru** [comment]
FIX:
```brew install pygtk```
Adding the PYTHONPATH to your .bashrc or (if you use zsh, .zshrc) would fix the issue.
i.e.
``` export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH ```

**Comment by adityathiru** [comment]
Closing the issue as of now since we're currently focussing on implementing the web interface.

**Comment by vik-y** [comment]
Don't close it. Since the GUI is working on MAC also we can atleast work on fixing the Downloads from GUI.

**Comment by adityathiru** [comment]
Okay bhai. From what @adishegde says, #1 is fixed. Once we test it from our end and merge it, he can start working on this.

**Comment by adityathiru** [comment]
@adishegde @jujusudhur 
One of you can work on fixing the downloads for macOS other can take up linux. We'll deal with windows later on. This can be your task for this week (by next Sunday), since you guys are done with your previous tasks.
Comment over here on what platform you want to take up.

**Comment by adishegde** [comment]
I'll try fixing it for macOS.
